import './ui/globals.css'
import { poppins } from './fonts/fonts'
import Nav from './ui/nav'

export const metadata = {
  title: 'Yael Correa',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Nav/>
        {children}
      </body>
    </html>
  )
}
